### ISSUE TITLE
OpenAPI 3.0.3 outputs `schema: {}` instead of `$ref`

### ISSUE THREAD

**Issue by yoskhdia** [softwaremill/sttp-apispec#119]
Hello, thanks for this useful software !

After updating to the latest version, there is a problem where `$ref` is no longer used in the generated yaml files.
Is there a workaround?

# versions

```
      "com.softwaremill.sttp.tapir" %% "tapir-core" % "1.8.0",
      "com.softwaremill.sttp.tapir" %% "tapir-openapi-docs" % "1.8.0",
      "com.softwaremill.sttp.apispec" %% "openapi-circe-yaml" % "0.7.0"
```

# problem

```scala
case class FooRequest(a: String)
endpoint.in(jsonBody[FooRequest])
```

`OpenAPIDocsInterpreter().toOpenAPI(endpoint, info).toYaml3_0_3` outputs

```
      requestBody:
        content:
          application/json:
            schema: {}
```

`OpenAPIDocsInterpreter().toOpenAPI(endpoint, info).toYaml` outputs

```
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FooRequest'
```

# expect

`.toYaml3_0_3` will still output `$ref` as before.

**Comment by adamw** [comment]
Sorry, my bad. I'll release an update to apispec and tapir :)

**Comment by yoskhdia** [comment]
Thank you for your quick response! 😄
