### ISSUE TITLE
OpenAPI: wrong key for example field when the schema represents an iterable

### ISSUE THREAD

**Issue by hygt** [softwaremill/sttp-apispec#49]
Hello,

Sometime between the version 0.2 and 0.3 you changed the way a schema's `example` field is encoded:
https://github.com/softwaremill/sttp-apispec/blob/master/jsonschema-circe/src/main/scala/sttp/apispec/internal/JsonSchemaCirceEncoders.scala#L63

However using `examples` for all instances of `ExampleMultipleValue` seems wrong, for instance this type is used by Tapir in `SArray`'s `encodedExample`: https://github.com/softwaremill/tapir/blob/master/docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/package.scala#L39

Minimal reproducible example, runnable with scala-cli: https://gist.github.com/hygt/62011e6ed5b641c4f3dcf9408b79840d

This outputs:
```yaml
openapi: 3.0.3
info:
  title: title
  version: '1.0'
paths:
  /:
    get:
      operationId: getRoot
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
components:
  schemas:
    Foo:
      required:
      - id
      type: object
      properties:
        id:
          type: string
        codes:
          type: array
          items:
            type: integer
            format: int32
          examples:
          - 1
          - 2
          - 3
```

Which fails to validate using https://validator.swagger.io/#/Validator/reviewByContent:
```
---
messages:
- "attribute components.schemas.Foo.examples is unexpected"
schemaValidationMessages:
- level: "error"
  domain: "validation"
  keyword: "oneOf"
  message: "instance failed to match exactly one schema (matched 0 out of 2)"
  schema:
    loadingURI: "#"
    pointer: "/definitions/Components/properties/schemas/patternProperties/^[a-zA-Z0-9\\\
      .\\-_]+$"
  instance:
    pointer: "/components/schemas/Foo"
  required: null
  missing: null
````

Reverting to an older version of Tapir using apispec 0.2.1 fixes the issue, such as Tapir 1.1.0.

I'm not super familiar with the OpenAPI specification but maybe we need three kinds of `ExampleValue`, something like `ExampleSingleValue`, `ExampleMultipleValue` and an additional `ExampleIterableValue`?

**Comment by adamw** [comment]
I think the problem is different, currently our model allows only a single example in `Schema`. There might be multiple examples added to tapir's inputs/outputs (which are represented in the docs on a single level). So I think we should always use `example`.

**Comment by adamw** [comment]
See also https://github.com/softwaremill/tapir/pull/2676
