### ISSUE TITLE
json-schema missing title property

### ISSUE THREAD

**Issue by dvgica** [softwaremill/sttp-apispec#80]
The new ability to generate JSON Schema from Tapir `Schema` is very nice! The one thing I've found missing so far is the `title` [property](http://json-schema.org/understanding-json-schema/reference/generic.html#id2). While I suspect it isn't very useful for OpenAPI, it's very useful when viewing a JSON Schema in something like json-schema.app. Without the `title`, a bunch of nested objects just show up as `object` which makes things pretty un-navigable. The `scala-jsonschema` lib supports it [like this](https://github.com/andyglow/scala-jsonschema#annotations). By default, filling in `title` with the same string as the definition name would work well I think.

**Comment by katlasik** [comment]
@dvgica One question to make sure, we're on the same page. You want json output like this:

```
....
 "$defs" : {
     "Child" : {
        "title" : "Child",
        "required" : ["example"],
...
```

**Comment by dvgica** [comment]
Yes, exactly.

**Comment by katlasik** [comment]
Should be implemented with https://github.com/softwaremill/tapir/pull/3001. 
By default title will be the name of definition, but you can also customize it with @title annotation.

**Comment by katlasik** [comment]
Will be released with next version of tapir, if there will be any problems, please create another gh issue.

**Comment by dvgica** [comment]
Awesome, looks great @katlasik. Thanks so much!
